### ISSUE TITLE
Deduplicate - Remove duplicates from list

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#136] opened 2022-08-25 22:36 UTC
Reported in #39

1. [Remove duplicates from list](https://www.codewars.com/kata/57a5b0dfcf1fa526bb000118)
* 8 kyu
* input is array of numbers, output is expected to keep order of appearance
* 93% with ~18k completions
* 3 pending issues
* 8 languages + 3 pending translations
* Published Aug 2016, author last active May 2022

2. [Remove Duplicates](https://www.codewars.com/kata/53e30ec0116393fe1a00060b)
* 7 kyu
* input is array of numbers, output is expected to keep order of appearance
* 91% with 6.6k completions
* 1 pending issue of no random tests
* 7 languages, no pending translations
* Published Aug 2014, author inactive

3. [Unique numbers](https://www.codewars.com/kata/568f9bd9cbe89334c900000c)
* 7kyu
* input is array of numbers, output is expected to keep order of appearance
* 93% with 1.2k completions
* No pending issues
* 2 languages, 1 pending translation
* Published Jan 2016, author inactive

4. [Filter the array into unique values in 38 chars](https://www.codewars.com/kata/59d9707c2a7acce03900001b)
* 7 kyu
* Code golf
* 83% with ~400 completions
* No pending issues
* JS only, Python translation reported in discourse
* Published Oct 2017, author active

5. [Simple remove duplicates](https://www.codewars.com/kata/5ba38ba180824a86850000f7)
* 7 kyu
* requires output to be in order of _last_ appearance
* 91% with 8.5k completions
* 1 pending issue
* 17 languages + 1 pending translation
* Published Sep 2018, author active

6. [No Duplicates Here](https://www.codewars.com/kata/5592fcbf71f21d976a000011)
* beta with votes breakdown leaning towards 7 kyu
* heterogenous input arrays, sorted output, confusing rules regarding equality and ordering of elements
* 85% with 500 completions
* 1 pending issue
* 3 approved languages, I did not check pending translations
* Published Jun 2015, author inactive

-----

### Conclusion

- Keep 1. [Remove duplicates from list](https://www.codewars.com/kata/57a5b0dfcf1fa526bb000118)
- Keep 5. [Simple remove duplicates](https://www.codewars.com/kata/5ba38ba180824a86850000f7)
- [x] Retire 2. [Remove Duplicates](https://www.codewars.com/kata/53e30ec0116393fe1a00060b)
- [x] Retire 3. [Unique numbers](https://www.codewars.com/kata/568f9bd9cbe89334c900000c)
- [x] Retire 4. [Filter the array into unique values in 38 chars](https://www.codewars.com/kata/59d9707c2a7acce03900001b)
- [x] Retire 6. [No Duplicates Here](https://www.codewars.com/kata/5592fcbf71f21d976a000011)

### Filling gaps

- [x] Move LUA translation from 2. to 1.

**Comment by hobovsky** [comment] 2022-08-25 22:46
Kata 4. is code golf, and I did not bother to solve it. If golfing community thinks it's OK, it can stay.

Kata 5. seems to be the most interesting, and has many languages. I think it is good to keep.

I did not solve kata 6., but it's reportedly bad enough to get rid of it.

Kata 1., 2., and 3. seem to be almost exact duplicates. If we want to keep any of them, I think 1. would be good to keep because of its rank and selection of languages. But maybe all three could be retired in favor of 5.?

**Comment by KayleighWasTaken** [comment] 2022-08-25 23:02
Keep 1, 4 and 5. 2 and 3 are exact duplicates of 1, just yeet them. 1 is a good 8kyu task, 5 is a good 7kyu extension of 1. 4 is code golf so its distinct enough.

**Comment by Kacarott** [comment] 2022-08-26 06:30
Keep only 5. It has the most languages, and is the most interesting.

Regarding the codegolf kata, this should be retired. Its limit is quite relaxed, and the technique it asks for is used extensively in the JS solutions of any other similar non-golf kata, making it no more than a duplicate in my opinion.

**Comment by monadius** [comment] 2022-08-26 16:50
Keep 1 and 5. 4 is a trivial codegolf kata and its solution is a top-voted solution of 1.

**Comment by EloiseRosen** [comment] 2022-08-26 22:10
I really did not like 4 and 6 and vote to retire those. I don't have strong opinions on the others.

**Comment by ejini6969** [comment] 2022-08-27 02:03
Keep 1 && 5 due to reasons stated above

**Comment by Blind4Basics** [comment] 2022-08-28 14:45
keep 1 and 5 only

**Comment by Yang-Wei-Ting** [comment] 2022-08-31 11:28
Vote to retire 6. The reason is the same as the above mentioned.

**Comment by heroicfun** [comment] 2022-09-03 07:46
its kata is possible duplicate of:
https://www.codewars.com/kata/54e6533c92449cc251001667
because, description says that order in deduplicated array stay the same

**Comment by heroicfun** [comment] 2022-09-03 07:54
about my opinion: i think we should stay 1 and 5, because 1 has many completitions and 5 has good language coverage

**Comment by hobovsky** [comment] 2022-09-05 07:58
We keep 1. and 5. then.

**Closed as completed** 2022-09-07 05:29 UTC
Labels: discussion/deduplicate
