### ISSUE TITLE
Kata trial - "Being Wordy"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#174] opened 2023-02-08 22:56 UTC
Kata [Being Wordy](https://www.codewars.com/kata/5900f47f9a1d60510c00009f/) has been reported as a candidate for deduplication together with kata [No Order of Operations](https://www.codewars.com/kata/5e9df3a0a758c80033cefca1/), but while creating a deduplication ticket I realized that these two are not necessarily duplicates.  I did not manage to solve "Being Wordy" with the approach I used for "No order of operations", but after solving the former, I was able to tweak the solution to pass the latter. "Being Wordy" is more complex than "No Order of Operations", but unfortunately its execution is far from good and currently, it's a user experience nightmare.

What to do with [Being Wordy](https://www.codewars.com/kata/5900f47f9a1d60510c00009f/)? There's several options:
1. Leave as it is, nothing needs to be done.
2. Keep it approved as it is now, and fix - fixing can be difficult because spec is quite bloated and creating tests with good coverage which would be infeasible to hardcode can require a lot of effort.
3. Un-approve, move back to beta, and wait until someone decides to fix it - pros: it's not likely to be auto-retired as hopeless, cons: it will probably never reach approvable state
4. Retire as unsalvageable
5. Retire as a duplicate of [No Order of Operations](https://www.codewars.com/kata/5e9df3a0a758c80033cefca1/)
6. Something else?

Frankly, I liked the idea and the task of the kata. However I think the kata can be too much effort to fix.

-----

### Conclusion

- [x] Retire [Being Wordy](https://www.codewars.com/kata/5900f47f9a1d60510c00009f/)

**Comment by ejini6969** [comment] 2023-02-09 09:13
Apart from the issues stated in discourse, it is also over-ranked (should be 6kyu conforming to current standards) and the usage of classes and methods are just applying the technique of "mixing this and that to make kata unique" that adds nothing new nor interesting for users.

I would vote for **4 / 5** as it is pointless to fix it as it will eventually become too similar to the other linked kata above (one can just replace `plus` with `+` etc. and remove irrelevant words to solve the task same as the linked kata)

**Comment by EloiseRosen** [comment] 2023-02-18 21:33
I vote for 5: Retire as a duplicate of No Order of Operations.

**Comment by akar-0** [comment] 2023-02-22 13:37
I vote 4: bad design though, maybe, _good idea_, but we are talking about keeping a kata, not an idea.

**Comment by hobovsky** [comment] 2023-02-28 21:23
With 5 votes to retire and no opposite opinions I think retiring the kata will be OK.

**Closed as completed** 2023-03-07 18:42 UTC
Labels: discussion/kata-trial
