### ISSUE TITLE
Deduplicate "derivative polynomial"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#57] opened 2022-01-19 14:14 UTC
1. [Calculate the derivative of a polynomial](https://www.codewars.com/kata/56d060d90f9408fb3b000b03)
  *  5 kyu
  * Polynomials with multiple terms
  * Python only, no pending translations
  * 163 solutions, 91% satisfaction
  * Author last active 4 months ago
  * Published Feb 2016
  * No pending issues
2. [Derivatives of type x^n](https://www.codewars.com/kata/55e2de13b668981d3300003d)
  * 6 kyu
  * Much simpler tasks, the input polynomial has only one term
  * Javascript and Coffeescript, pending Java translation
  * 113 solutions, 93% satisfaction
  * Author inactive
  * Published Sep 2015
  * No pending issues, ~~but has one complaint which I cannot see and which probably could be fixed~~ (the complaint is not really valid)
3. [Calculate Derivative #1 - Single Integer Equation](https://www.codewars.com/kata/5a0350c380171ffd7b00012a)
  * 7 kyu
  * The same task as above (polynomials with just a single term)
  * Python and Ruby
  * 187 solutions, 93% satisfaction
  * Author deleted
  * Published Nov 2017
  * Pending issue about poor tests

One question is: is 1. a duplicate of 2. and 3. , as it has more complex inputs?

Bonus discussion:
- Is [Take the Derivative](https://www.codewars.com/kata/5963c18ecb97be020b0000a2) a duplicate too?
- Is [Differentiate a polynomial](https://www.codewars.com/kata/566584e3309db1b17d000027) a duplicate too?

--------

Conclusion:

 - [x] Retire [Calculate Derivative #1 - Single Integer Equation](https://www.codewars.com/kata/5a0350c380171ffd7b00012a) as a duplicate of 2. and low quality.
 - I think the discussion did not sufficiently conclude that 1. and 2. are duplicates, so both stay for now.

**Comment by hobovsky** [comment] 2022-01-19 14:44
My opinion:
- I am not 100% sure if 2. and 3. are duplicates of 1., but I vote yes. My first vote is to retire 2. and 3. as (over)simplified duplicates of 1.
- Even if sufficiently different from 1., 2. and 3. are clear duplicates of each other. They differ by rank, and I am not really sure which is more appropriate, but I'm leaning towards the 6 kyu one because it has edge cases like `"-x"` and `"42"`. My vote is to retire 3. and _eventually_ keep 2.

I think the kata from "bonus" section are not clear duplicates and can be discussed separately, but feel free to express your opinion.

**Comment by ejini6969** [comment] 2022-01-19 14:58
IMO ~~
* 3. is a subset of 2. so it should definitely be retired.
* As for 2. , though it accounts for edge cases as u mention but keeping it will be too similar with 1. (With 1. having an additional requirement of `+` sign which can easily be solved using split and perform summation using the function in 2.)
* As for [Differentiate a polynomial](https://www.codewars.com/kata/566584e3309db1b17d000027), it is a duplicate of 1. as it is basically the same except it needs extra conversion of `x` to the given number and perform arithmetic calculations. The former being abit overranked while the latter has only one language (Python) so to decide which one to keep might need further discussion ~~
* [Take the derivative](https://www.codewars.com/kata/5963c18ecb97be020b0000a2) is not a duplicate of any of them as it is a mixture of string combination & understanding how derivatives work ~~ (beginner friendly)

**Comment by hobovsky** [comment] 2022-01-19 15:32
> The latter being abit overranked while the former has only one language (Python) so to decide which one to keep might need further discussion

I am personally not really bothered about differences of available languages. Translations will come, sooner or later. Or, we could agree that transferring translations to a target kata might be a prerequisite for retirement of the other.

**Comment by ejini6969** [comment] 2022-01-19 15:41
> I am personally not really bothered about differences of available languages. Translations will come, sooner or later. Or, we could agree that transferring translations to a target kata might be a prerequisite for retirement of the other.

Agreed. Transferring languages from the 5kyu one to the 4kyu is easy, but not as easy as doing the other way around. It requires changing reference solution, adding extra parameter for random integer (positive / negative) and account for arithmetic overflow(?) But I believe it should not be a problem with the help of community !

**Comment by twilight-sun** [comment] 2022-01-19 18:59
in that 7kyu one (3. in list) tests in Ruby are just bad, there are tests like
_Testing: 0x^27; Expecting: 0x^26
Testing: 139x^0; Expecting: 0x^-1_
that is inconsistent with description, sample tests and common sense

**Comment by Blind4Basics** [comment] 2022-01-20 08:16
* retire 3 (dup + bad tests)
* I don't mind 2, as an entry task on the topic, but that wouldn't bother me either if it was retired
* 1 and the 4kyu: yeah, they are too close to each others, even if I see them farther from each other than ejini6969, with the evaluating part. I'd personnally keep the 4 kyu because more sovles and languages, and the tests are good, afaik.

**Closed as completed** 2022-01-26 21:25 UTC
Labels: discussion/deduplicate

**Comment by hobovsky** [comment] 2022-01-26 23:52
Created #72 as a follow-up.
