### ISSUE TITLE
Deduplicate - Rearrange into a palindrome

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#124] opened 2022-08-17 21:32 UTC
Reported in #39

1. [Permute a Palindrome](https://www.codewars.com/kata/58ae6ae22c3aaafc58000079)
* 6kyu
* 95% with 1.2k completions
* 2 pending issues
* 5 languages (C, D exclusive) + 3 pending translations (Go, Rust, C++ exclusive)
* Published Feb 23, 2017, author active

2. [Simple Fun #68: Palindrome Rearranging](https://www.codewars.com/kata/5893fa478a8a23ef82000031)
* 7kyu
* 94% with 550+ completions
* No pending issues
* 4 approved languages (C# exclusive), no pending translations
* Published Feb 3, 2017, author active

3. [Numerical Palindrome #5](https://www.codewars.com/kata/58e26b5d92d04c7a4f00020a)
* 6kyu
* Valid inputs are only integers. Tests for invalid inputs like negative numbers, strings, single digit numbers(!)
* 93% with ~1k completions
* 3 pending issues
* 4 languages (COBOL exclusive) + 1 pending translation (PHP exclusive)
* Apr 2017, author last active May 2022

----

### Conclusion

- Keep 1. [Permute a Palindrome](https://www.codewars.com/kata/58ae6ae22c3aaafc58000079)
- [x] Retire 2. [Simple Fun #68: Palindrome Rearranging](https://www.codewars.com/kata/5893fa478a8a23ef82000031)
- [x] Retire 3. [Numerical Palindrome #5](https://www.codewars.com/kata/58e26b5d92d04c7a4f00020a) after PHP translation gets moved.

### Filling gaps

- [x] Move C# approved translation from 2. to 1.
- [x] Move COBOL approved translation from 3. to 1.
- [x] Move PHP pending translation from 3. to 1.

**Comment by hobovsky** [comment] 2022-08-17 21:42
To be frank, I dont like any of the kata.
All of the three are disappointing in terms of performance requirements. 6 kyu deserves smarts.
Kata 1. and 2. are almost identical with the difference that JS version of 1. has some (two?) fixed large tests. 
Kata 3. has valid inputs limited to numbers, but tests test also for strings (which are invalid input, even if they are a palindrome), negative numbers which are invalid input,  and for some unexplainable reason, numbers 0-9 are a valid input, but are _not_ considered palindromes :thonking:

I vote to keep 1. only because of most available languages. I vote to retire 2. as a duplicate of 1., and retire  3. as not much different from 1. and 2., especially for a 6 kyu.

**Comment by monadius** [comment] 2022-08-17 23:15
1 is a good kata and naive solutions do not work there. So it has performance requirements. `O(n^2)` solutions work but it is not a good idea to prohibit them because the main point of the kata is to get something better than `O(n!)` solutions.

Definitely keep 1. Definitely retire 2 (because its description is almost literally copied from Codesignal). Also retire 3 because it is a duplicate of 1 which also has annoying input validation requirements.

**Comment by hobovsky** [comment] 2022-08-17 23:18
> 1 is a good kata and naive solutions do not work there. So it has performance requirements.

Did you check if all language versions require performant solution?

**Comment by hobovsky** [comment] 2022-08-17 23:20
> `O(n^2)` solutions work but it is not a good idea to prohibit them because the main point of the kata is to get something better than `O(n!)` solutions.

Sounds reasonable, thanks for input.

**Comment by monadius** [comment] 2022-08-17 23:20
All languages test sufficiently long strings so `O(n!)` are not possible.

**Comment by ejini6969** [comment] 2022-08-18 01:45
Retire 2 (due to copyright issues & being 7kyu) && 3 (due to annoying input validation)

Actually, the entire series has that annoying input validation for no reason...

**Comment by Kacarott** [comment] 2022-08-18 05:54
Keep 1, retire 2, and super-retire 3.

"Single digit numbers are not palindromes" pssshhhh

**Comment by KayleighWasTaken** [comment] 2022-08-18 14:26
Keep 1. Retire 2 and 3. Opinions are the same as those already been raised above.

**Comment by EloiseRosen** [comment] 2022-08-21 12:56
Doing 3 gave me an eye twitch. Keep 1, retire the others.

**Closed as completed** 2022-09-26 22:12 UTC
Labels: discussion/deduplicate
