### ISSUE TITLE
Retire - Pole Vaulting Starting Marks

### ISSUE THREAD

**Issue by CodingComrade** [codewars/content-issues#153] opened 2022-09-27 18:36 UTC
https://www.codewars.com/kata/5786f8404c4709148f0006bf

This kata is an excellent linear algebra problem, but I don't think it's an appropriate coding challenge as the focus is more on understanding a mathematical formula rather than programming fundamentals. These kinds of katas could discourage beginners. Maybe it could be rewritten to include the formula. As it stands right now, even someone that understands linear algebra might have trouble understanding what exactly they are supposed to do to solve the kata. 

Vote 👍 to keep the kata, 👎 to retire.

**Comment by hobovsky** [comment] 2022-09-27 18:46
This kata has been discussed already a couple of times and i always argued to keep it. I think its a good task which can be solved with a computer. I will try to find some opinions i wrote on it and add them here.

Maybe the kata could be improved in some way, but I definitely think it does not deserve retirement just because it's related to algebra, or any other math topic.

**Comment by hobovsky** [comment] 2022-09-27 20:36
Oh, it seems this discussion is a duplicate of https://github.com/codewars/content-issues/issues/106 .  I am going to close this one as a duplicate, and if you want to continue, please post on #106 and then I will reopen it for further discussion.

**Closed as completed by hobovsky** 2022-09-27 20:36 UTC
Labels: duplicate-issue
