### ISSUE TITLE
Deduplicate - Greatest Common Divisor

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#64] opened 2022-01-23 13:17 UTC
These two kata are exact duplicates:

1. [Greatest common divisor](https://www.codewars.com/kata/5500d54c2ebe0a8e8a0003fd)
* 7kyu,
* 90% satisfaction, 12.5k solutions
* No pending issues 
* 11 languages, no pending translations 
* Published Mar 2015, author inactive

2. [Find the GCF of Two Numbers](https://www.codewars.com/kata/579e3476cf1fa55592000045)
* 7kyu,
* 84% satisfaction, ~1100 solutions
* 2 pending issues
* 6 languages + 4 pending translations. All approved languages are available in 1.
* Published Jul 2016, author inactive

For the record, this draft:

3. [All Star Code Challenge #11](https://www.codewars.com/kata/58646b6439c5ab22fb0000e0)

--------

Conclusion:

- [x] Retire [Find the GCF of Two Numbers](https://www.codewars.com/kata/579e3476cf1fa55592000045) as a duplicate of 1.
- Keep [Greatest common divisor](https://www.codewars.com/kata/5500d54c2ebe0a8e8a0003fd), transfer to it languages available only in 2. (TypeScript pending translation).

**Comment by Blind4Basics** [comment] 2022-01-23 13:34
retire 2

(note: why pointing at 3 since it's a draft?)

**Comment by ejini6969** [comment] 2022-01-23 13:47
Retire 2nd due to lower completion, lesser language and several issues

Note: the 2nd language has 4 pending translations with 3 of them already available in first. So TS translation can be ported to there.

**Comment by hobovsky** [comment] 2022-01-23 14:04
> Retire 2nd due to lower completion, lesser language and several issues
> 
> Note: the 2nd language has 4 pending translations with 3 of them already available in first. So TS translation can be ported to there.

Exactly what I wanted to suggest.

**Comment by imjasonmiller** [comment] 2022-01-23 14:10
I’d remove the second one, agree with @ejini6969.

**Comment by CiprianAmza** [comment] 2022-01-23 15:20
Retiring 2 looks like the best option here.

**Comment by EloiseRosen** [comment] 2022-01-23 18:42
Some others that are similar:
* [Greatest Common Divisor Bitcount](https://www.codewars.com/kata/54b45c37041df0caf800020f) (7kyu) is the same as 1 and 2 except you have to convert to binary and count the 1s after. 
* [GCD Matrix](https://www.codewars.com/kata/58a30be22d5b6ca8d9000012) (7kyu) is the same except you have to get GCD for pairs of numbers and then round
* [Greatest Common Factor of an Array](https://www.codewars.com/kata/5849169a6512c5964000016e) (6kyu) is the same idea except applied to an array
* [Get Smallest Common Factor](https://www.codewars.com/kata/5933af2db328fbc731000010) (7kyu) is smallest instead of largest

These are less identical than 1 and 2 - feel free to ignore if they're different enough to keep

**Comment by ejini6969** [comment] 2022-01-24 01:09
> Some others that are similar:

> *Greatest Common Divisor Bitcount (7kyu) is the same as 1 and 2 except you have to convert to binary and count the 1s after.
 *GCD Matrix (7kyu) is the same except you have to get GCD for pairs of numbers and then round
*Greatest Common Factor of an Array (6kyu) is the same idea except applied to an array
*Get Smallest Common Factor (7kyu) is smallest instead of largest

> These are less identical than 1 and 2 - feel free to ignore if they're different enough to keep

The last 2 has already been considered duplicate to each other in another category. 
If the 1st is considered as well, then CW white level katas are considered duplicate of one another OwO
The 2nd one requires more operations in calculating the final average gcd value.

**Comment by EloiseRosen** [comment] 2022-01-25 00:10
Ok, makes sense!

**Closed as completed** 2022-01-31 20:12 UTC
Labels: discussion/deduplicate
