### ISSUE TITLE
Deduplicate "valid braces"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#59] opened 2022-01-20 03:37 UTC
* [Valid Braces](https://www.codewars.com/kata/5277c8a221e209d3f6000b56)
  * 6 kyu
  * input is `()[]{}`
  * 45k completions, 91% satisfaction
  * 17 languages + 4 pending translations
  * 17 pending issues, but most probably some are obsolete. Missing tests for some edge cases in some languages.
  * published Nov 2013, author inactive 

* [Checking Groups](https://www.codewars.com/kata/54b80308488cb6cd31000161)
  * 6 kyu
  * input is `()[]{}`
  * 7k completions, 90% satisfaction
  * 6 languages
  * 4 pending issues, two about missing random tests
  * published Jan 2015,  author inactive 

Bonus discussion:

* [Valid Parentheses](https://www.codewars.com/kata/52774a314c2333f0a7000688) - is this a duplicate of two above?
  * Severely over-ranked at 5kyu
  * input only consists of `()`
  * 70k completions, 91% satisfaction

---------

Conclusion:

- [x] Retire [Checking Groups](https://www.codewars.com/kata/54b80308488cb6cd31000161) as a duplicate of [Valid Braces](https://www.codewars.com/kata/5277c8a221e209d3f6000b56)
- I am not sure how to handle reranking of a kata with ~70k solutions, so [Valid Parentheses](https://www.codewars.com/kata/52774a314c2333f0a7000688) will stay 5 kyu for now.

**Comment by hobovsky** [comment] 2022-01-20 04:03
My vote:
- Keep "Valid braces" as more complete with its large variety of languages
- Retire "Checking Groups" as a duplicate
- "Valid Parentheses" allows for simpler approach, and IMO is not a duplicate of two above, albeit seriously overranked. We can ask to re-rank it, but I am afraid that with this many solutions it won't be easy.

**Comment by ejini6969** [comment] 2022-01-20 05:08
i) 2. should be retired due to being exact duplicate of 1. 
~~ii) 3. is indeed a duplicate of the above 2 since it only requires a small tweak on existing solutions. (The use of regex, indexing, string replacement or stack pop / push are identical operations)~~

EDIT: 3 should be kept unless reranking not possible

**Comment by monadius** [comment] 2022-01-20 05:18
3 is definitely not a duplicate of 1 and 2 but it is overranked. The preferred solution of 3 is not applicable to other two kata.

**Comment by ejini6969** [comment] 2022-01-20 05:36
Okay I understand that it's not conceptually a duplicate since the idea is somewhat different. Some solutions also use a different approach, but we are talking from a different context. I considered several solutions copied from that kata can be tweaked to fit into the other one as duplicate, unless those solutions are less enough that mods can filter and hide them.

**Comment by monadius** [comment] 2022-01-20 05:42
It is better to view 3 as a simpler version of 1 and 2. We have many kata like this. And I don't want any kata to be retired only because cheaters exist. Moreover, solutions of 3 are sufficiently different from 1 and 2.

**Comment by Blind4Basics** [comment] 2022-01-20 07:44
* retire 2
* rerank 3 at 6 or 7 kyu (since the O(N²) can pass, or retire it if not possible to rerank?

**Comment by monadius** [comment] 2022-01-21 01:26
I think that we all agree that 2 should be retired. Ideally, 3 should also be re-ranked (I vote for 7 kyu).

**Comment by Kacarott** [comment] 2022-01-21 18:02
I agree, both with keeping 1, and reranking 3 to 7 kyu

**Comment by krishsharma0413** [comment] 2022-01-24 16:05
keep **Valid Parentheses** but derank to 6kyu, derank **valid braces** to 7kyu and remove **checking groups**.

**parantheses** is over ranked in python maybe to 6kyu?, **checking groups** have an extra check that isnt in **valid braces** but **valid braces** have more langs.

my opinion but as if it matters. (╯°□°）╯︵ ┻━┻

**Closed as completed** 2022-01-24 20:38 UTC
Labels: discussion/deduplicate
