### ISSUE TITLE
Deduplicate - Generate array of integers of certain length

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#162] opened 2022-11-06 23:22 UTC
From #39

Inputs are valid unless specified otherwise.  
Notation is: `[x...y)` for `x` inclusive, `y` exclusive.
`start` is less than `end` in almost all kata, unless specified otherwise.
All kata ask for a filled array/list, no kata asks explicitly for lazy generators.

1. [Filling an array (part 1)](https://www.codewars.com/kata/571d42206414b103dc0006a1)
* `[0...n)`, param is optional
* 8 kyu
* 89% with 25.8k completions
* 1 pending issue
* 15 languages, 3 pending translations
* Published Apr 2016, author inactive

2. [Series of integers from 0 to n](https://www.codewars.com/kata/5841f4fb673ea2a2ae000111)
*  `[0...n]`
* 7 kyu
* 89% with ~2700 completions
* 1 pending issue (About 3 languages needing an update)
* 7 languages, 1 pending translation
* Published Dec 2016, author inactive

3. [Count the Monkeys!](https://www.codewars.com/kata/56f69d9f9400f508fb000ba7)
* `[1...n]`
* 8 kyu
* 92% with ~48k completions
* 2 pending issues
* 28 languages, no pending translations
* Published Mar 2016, author active

4. [Pre-FizzBuzz Workout #1](https://www.codewars.com/kata/569e09850a8e371ab200000b)
* `[1...n]`
* 8 kyu
* 91% with ~15.7k completions
* No pending issues
* 9 languages, 3 pending translations
* Published Jan 2016, author inactive

5. [Unfinished Loop - Bug Fixing #1](https://www.codewars.com/kata/55c28f7304e3eaebef0000da)
* bug fixing, `[1...n]`
* 8 kyu
* 87% with ~30k completions
* 2 pending issues
* 9 languages, no pending translations
* Published Aug 2015, author inactive

6. [Extra Perfect Numbers (Special Numbers Series #7)](https://www.codewars.com/kata/5a662a02e626c54e87000123)
* `[1...n] : step=2`, but disguised
* 7 kyu
* 86% with ~5k completions
* 1 pending issue + bad formatting of description
* 33 languages(!), 1 pending translation
* Published Jan 2018, author inactive

7. [Reversed sequence](https://www.codewars.com/kata/5a00e05cc374cb34d100000d)
* `[n...1]`
* 8 kyu
* 92% with ~72.5k completions
* 1 pending issue
* 25 languages, 2 pending translations
* Published Nov 2017, author last active Sep 2022

8. [Sequence to 1](https://www.codewars.com/kata/5a05fe8a06d5b6208e00010b)
* `[n...1]`, ascending or descending depending on `n > 1` 
* 7 kyu
* 85% with ~750 completions
* No pending issues
* 5 languages, no pending translations
* Published Nov 2017, author last active Sep 2022 (same as 7).

9. [Get the integers between two numbers](https://www.codewars.com/kata/598057c8d95a04f33f00004e) 
* `(start...end)`
* 7 kyu
* 92% with ~2.8k completions
* No pending issues
* 6 languages, no pending translations
* Published Aug 2017, author inactive

10. [Series of integers from m to n](https://www.codewars.com/kata/5841f680c5c9b092950001ae)
* `[start...end]`
* 7 kyu
* 91% with ~5k completions
* No pending issues
* 8 languages, no pending translations
* Published Dec 2016, author inactive (the same as 2.)

11. [What is between?](https://www.codewars.com/kata/55ecd718f46fba02e5000029)
* `[start...end]`
* 8 kyu
* 93% with ~33.2k completions
* No pending issues
* 20 languages, 2 pending translations
* Published Sep 2015, author inactive

12. [Generate range of integers](https://www.codewars.com/kata/55eca815d0d20962e1000106)
* `[start...end] : step`
* 8 kyu
* 93% with ~21k completions
* 2 pending issues
* 12 languages, 3 pending translations
* Published Sep 2015, author inactive

13. [Find Multiples of a Number](https://www.codewars.com/kata/58ca658cc0d6401f2700045f)
* `[start....end] : step=start` (multiplies of `start` up to `end`)
* 8 kyu
* 93% with ~22.6k completions
* No pending issues
* 14 languages + 5 pending translations
* Published Mar 2017, author inactive

14. [From-To-Step Sequence Generator](https://www.codewars.com/kata/56459c0df289d97bd7000083) 
* `[start...end] : step`, order depends on `start < end`. `step == 0` is invalid input.
* 7 kyu
* 90% with ~900 completions
* 1 pending issue
* 3 languages
* Published Nov 2015, author inactive

----

### Conclusion

- [x] Retire 1. [Filling an array (part 1)](https://www.codewars.com/kata/571d42206414b103dc0006a1)
- [x] Retire 2. [Series of integers from 0 to n](https://www.codewars.com/kata/5841f4fb673ea2a2ae000111)
- Keep 3. [Count the Monkeys!](https://www.codewars.com/kata/56f69d9f9400f508fb000ba7)
- [x] Retire 4. [Pre-FizzBuzz Workout #1](https://www.codewars.com/kata/569e09850a8e371ab200000b)
- Keep 6. [Extra Perfect Numbers (Special Numbers Series #7)](https://www.codewars.com/kata/5a662a02e626c54e87000123)
- [x] Retire 9. [Get the integers between two numbers](https://www.codewars.com/kata/598057c8d95a04f33f00004e) 
- [x] Retire 10. [Series of integers from m to n](https://www.codewars.com/kata/5841f680c5c9b092950001ae)
- Keep 11. [What is between?](https://www.codewars.com/kata/55ecd718f46fba02e5000029)
- [x] Keep remaining kata as inconclusive and create a follow-up deduplication issue for them.

**Comment by hobovsky** [comment] 2022-11-06 23:38
This is a big list. I think there's also some attention necessary, because all kata are aimed at beginners, and some variety of the tasks could be good to have. Actual tasks span across more than one aspect (fixed step vs. variable step, ascending vs. descending vs. variable direction, inclusive vs. exclusive bounds), so it can be difficult to decide exactly what is a duplicate and what is not. Anyway, my take is:

* Kata 1.-4. are similar enough to get rid of all but one. I'd pick 3. as most complete, and retire 1., 2., and 4. Additionally, optional parameter in 1. can be problematic in translations to languages which do not support these.
* Kata 5. is bug fixing, and I would vote to keep it, but I don't like the quality of the presented bug. I will be fine with having it retired.
* Kata 6. gives a feeling of a different task, I think it can be kept due to amount of brain cycles it requires to come up with a solution.
* Kata 7. feels terribly dull, and I think it could be superseded by 8. Kata 7. has a lot of languages, but I would still vote to get rid of it because 8. is nicer, and languages are already provided by 3.
* Kata 9., 10., and 11. are very similar, and I think that 11. can be kept as the most complete, and 9. and 10. can be retired.
* I think kata 13. is good enough for this level of difficulty to be kept, but if others say it should go, I'm fine with this.
* Between kata 12. and 14. I like 14. more due to a nicer task, but again, 12. has many more languages. I have no strong opinion which to keep and which to retire, but I think I would like to keep 14. more, and retire 12. as unnecessary.

If anyone has another idea for categorization, or which kata to keep and which to retire, please share.

**Comment by ejini6969** [comment] 2022-11-07 01:47
Retire 
1st  (being dup of 3. && having optional parameter requirement which is hard to maintain)
2nd (being dup of 3. , language updates required && over-ranked at 7kyu)
4th (being dup of 3. && series is non-existent)
5th (being dup of 3. despite requires bug-fix on incremental / decremental statement which can be directly copied from many katas)
9th (being dup of 11. && over-ranked at 7kyu)
10th (being dup of 11. && over-ranked at 7kyu)
12th  (being dup of 11. with a minor tweak in incremental value)
13th (being dup of 11. with a minor tweak in incremental and starting value)

Keep
3. (due to high completion, many languages && less maintainence)
6. (due to many languages, idea is unique and many different solutions available)
8. (Exclusive from all above katas as positive and negative integers for `n` are given)
11. (due to many languages, high completion && having another similar kata might add some value for beginners)
14. (Exclusive from all above katas as positive and negative integers for `from`, `step` and `to` are given in which invalid inputs may occur)

-----------------------------------------------------------------------------------------------------------------------------------------
I'm not sure about 7, but if we want to get rid of it, I have no opinion. But if we decide to keep it, maybe we should retire 3 since it is the reverse operation of 7, plus 7 having higher completions!

**Comment by JohanWiltink** [comment] 2022-11-07 12:12
7 kyu is not overranked in all languages. E.g. in Javascript, 8 kyu is underranked.

**Comment by KayleighWasTaken** [comment] 2022-11-07 19:23
Retire 1, 2, 4 - (Near) direct dupes of 3.
Retire 5 - Dupe of 3 and the bug fixing aspect isn't compelling enough to keep in my opinion.
Retire 6 - Couldn't make it through the entirety of the Zizo's attempt at obfuscating the task with that description.
Retire 8 - Direct dupe for 7 with much lower completions and language count.
Retire 9, 10 - Direct dupes of 11 but with lower completion and language counts.

Keep 3 - Most complete of the basic task format and has the cutest story.
Keep 7 - More complete than 8.
Keep 11 - Most complete of its category.
Keep 12, 14 - Whilst there is some overlap, I think that 14's extra requirements can justify it staying as a 7kyu to go along with 12's 8kyu.
Keep 13 - Unique enough for me.

**Comment by benjaminzwhite** [comment] 2022-11-08 17:36
I agree with both ejini + Kayleigh "consensus" on: 

- **keep:** 3 out of the set {1,2,3,4}, 11, 14

- **retire:** {1,2,4}, 5, 9, 10

6 is in principle "interesting/different" but strong agree with Kayleigh on the Zizo description problem (if you rewrite the entire description, you'd presumably have to rewrite the others in the linked series also...)

No strong opinions on the others, but I'd tend towards removing more rather than fewer of them.

Finally - if 14 stays, I'll update Python test framework + add random tests. I also suggest we change the variable names (currently it uses **uppercase** `From` `To` `Step` , and note that `from` is a reserved keyword in Python also).

**Comment by EloiseRosen** [comment] 2022-11-09 01:31
my votes:
1-4: keep 3, retire the others
5: keep
6: keep
7-8: retire 7, keep 8
9-11: keep 11, retire the others
12, 14: keep 12, retire 14
13: retire

**Comment by heroicfun** [comment] 2022-11-13 12:21
my votes:
1-4, retire 1,2,4
3 keep
5, 6, 7 keep
8 retire, because it has less completions and covered languages(in 7, its count is 25, vs 5 on 8)
9-10 retire
11 keep
12 or 13: keep, retire 14

**Comment by hobovsky** [comment] 2023-01-16 10:05
This groups contains too many kata to get consensus on all of them, but there are 7 kata with unanimous votes, so we can at least conclude these:

- Retire 1., 2., 4., 9., 10.
- Keep 3., 6., 11.
- I will create a follow-up issue for kata which didn't get to conclusion in this round.

**Closed as completed** 2023-01-17 00:46 UTC
Labels: discussion/deduplicate
