### ISSUE TITLE
Deduplicate - count occurrence of a character in string

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#63] opened 2022-01-21 21:05 UTC
1. [All Star Code Challenge #18](https://www.codewars.com/kata/5865918c6b569962950002a1)
  * 8kyu
  * Case sensitive
  * Satisfaction 92%, ~21k solutions
  * No pending issues
  * 10 languages + 2 pending translations
  * Published Dec 2016, author inactive
  
2. [Count the Characters](https://www.codewars.com/kata/577ad961ae2807182f000c29)
  * 7kyu
  * Case insensitive
  * Satisfaction 90%, ~2,6k solutions
  * 1 pending issue
  * 5 languages, no pending translations
  * Published Jul 2016, author inactive

3. [How many times does it contain?](https://www.codewars.com/kata/584466950d3bedb9b300001f)
  * 7kyu
  * Case sensitive
  * Satisfaction 84%, ~2,1k solutions
  * 4 pending issues
  * 7 languages, no pending translations
  * Published Dec 2016, author inactive

---- 

### Conclusion

 - Keep 1. [All Star Code Challenge #18](https://www.codewars.com/kata/5865918c6b569962950002a1)
 - [x] Retire 2. [Count the Characters](https://www.codewars.com/kata/577ad961ae2807182f000c29)
 - [x] Retire 3. [How many times does it contain?](https://www.codewars.com/kata/584466950d3bedb9b300001f) after Haskell translation is moved.

### Filling gaps

- [x] Move Haskell approved translation from 3. to 1.

**Comment by hobovsky** [comment] 2022-01-21 21:30
My vote:
- Keep 1. as the most complete: best satisfaction, no issues, most languages, most solutions. I am not 100% sure about the rank, but I believe 8 kyu is either fine or not much off. Retire 2. and 3. as inferior duplicates of 1. 
- If you think that 2. or 3. is better because it's case-insensitive or ranked more accurately, then I have no preference.

**Comment by CiprianAmza** [comment] 2022-01-21 21:36
I vote for retiring only the 3rd one as an obvious duplicate of the first. The second one (even though it's almost the same) puts in scene the idea of "case insensitive", which may be interesting for beginners, so I would vote to keep the first two.

**Comment by Blind4Basics** [comment] 2022-01-21 21:58
keep 1 only, imo

**Comment by Kacarott** [comment] 2022-01-21 22:09
I agree to keep number one. I dislike the title and the strange note at the top of its description, but those could be changed, and otherwise it seems the best.

**Comment by ejini6969** [comment] 2022-01-22 02:04
I suggest to retire 3. due to being exact duplicate of 1. & 
2. as well since [solutions like this](https://www.codewars.com/kata/reviews/58672f1f50d0bb97a60008bb/groups/5868dc3f1d9ee198230002bf) and many more can be found in 1. which can pass the 2. test cases

I agreed the title of the description should be changed and description should mention that only lowercase strings will be tested (since it's a beginner level kata)

**Comment by ejini6969** [comment] 2022-01-22 02:39
BTW @hobovsky I don't think `substring` & `character` should be separated in deduplication since they used the same solution (in most languages) to solve the problem. If merging them together, then I think we can deduplicate 2 katas out of the 5 instead of 1 at the end of the day. (Sorry for being late to the party thooo ~~)

**Comment by hobovsky** [comment] 2022-01-23 10:48
Yes, i split these two groups because I believe that "count occurences of a char" and "count occurences of a substring" are generally not duplicate task.
They can be solved with identical solution only in languages which do not have a native character datatype and use single-character-strings in this place. But in languages which have proper characters, the problem calls for a different solution. You can do `haystack.count(needleChar)`, but you cannot do `haystack.count(needleSubstring)`.

**Comment by CiprianAmza** [comment] 2022-01-28 21:28
Looks like the common idea is to keep the first and to retire the third. Maybe the second one could be kept as well?

**Comment by EloiseRosen** [comment] 2022-02-12 00:18
vote for keep 1, retire 2 and 3.

**Comment by wtlgo** [comment] 2022-02-12 17:14
See no difference between 1 and 3, I didn't like the 2nd one because of the case-insensitivity requirement, which doesn't really make sense (it says "Count the Characters" even though `'a'` and `'A'` are in fact different characters).

**Closed as completed** 2022-10-12 21:02 UTC
Labels: discussion/deduplicate
